---- CUSTOMERAGENT TABLE ----
CREATE TABLE CUSTOMERAGENT
(
EMPID CHAR(6),
EMPNAME VARCHAR(50),
EMPEMAIL VARCHAR(50)

CONSTRAINT CUSTOMERAGENT_PK PRIMARY KEY(EMPID)
);

----CUSTOMERAGENT_PHONE TABLE ----
CREATE TABLE CUSTOMERAGENT_PHONE
(
EMPID CHAR(6),
EMPPHONENUMBER CHAR(10)

CONSTRAINT CUSTOMERAGENT_PHONE_FK FOREIGN KEY (EMPID) REFERENCES CUSTOMERAGENT(EMPID)

);

----REGISTER_USER TABLE ----

CREATE TABLE REGISTER_USER
(
USERID CHAR(6),
NIC CHAR(10) UNIQUE,
FIRST_NAME VARCHAR(50),
SECOND_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50)

CONSTRAINT REGISTER_USER_PK PRIMARY KEY(USERID)
);

----ADMIN TABLE ----

CREATE TABLE ADMIN
(
ADMIN_ID CHAR(6),
ADMIN_NAME VARCHAR(50),
ADMIN_EMAIL VARCHAR(50)

CONSTRAINT ADMIN_PK PRIMARY KEY (ADMIN_ID)
);

----ROOM TABLE ----

CREATE TABLE ROOM
(
ROOM_ID CHAR(6),
ROOM_TYPE VARCHAR(50)

CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID)
);

----ISSUES TABLE ----
CREATE TABLE ISSUES
(
REFERENCE_NO CHAR(6),
ISSUE_TYPE VARCHAR(50),
USERID CHAR(6)

CONSTRAINT ISSUES_PK PRIMARY KEY(REFERENCE_NO),
CONSTRAINT ISSUE_FK FOREIGN KEY(USERID) REFERENCES REGISTER_USER(USERID)
);

----CUSTOMERAGENT_ISSUE TABLE ----

CREATE TABLE CUSTOMERAGENT_ISSUE
(
REFERENCE_NO CHAR(6),
EMPID CHAR(6)
---   ----
CONSTRAINT CUSTOMERAGENT_ISSUE_FK1 FOREIGN KEY (REFERENCE_NO) REFERENCES ISSUES(REFERENCE_NO),
CONSTRAINT CUSTOMERAGENT_ISSUE_FK2 FOREIGN KEY (EMPID) REFERENCES CUSTOMERAGENT(EMPID)
);

----REGISTERUSER_PHONENO TABLE ----

CREATE TABLE REGISTERUSER_PHONENO
(
USERID CHAR(6),
PHONENUMBER CHAR(10)
--- ---
CONSTRAINT REGISTERUSER_PHONENO_FK FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID)
);

----PAYMENT TABLE ----
CREATE TABLE PAYMENT
(
PAYMENTID CHAR(6),
PAYMENT_TYPE VARCHAR(50),
AMOUNT FLOAT,
USERID CHAR(6),
ADMIN_ID CHAR(6)
CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENTID),
CONSTRAINT PAYMENT_FK1 FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID),
CONSTRAINT PAYMENT_FK2 FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

----PAYMENT_DATE TABLE ----

CREATE TABLE PAYMENT_DATE
(
DATE DATE,
PAYMENTID CHAR(6),
USERID CHAR(6)

--- ---
CONSTRAINT PAYMENTDATE_FK1 FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID),
CONSTRAINT PAYMENTDATE_FK2 FOREIGN KEY (PAYMENTID) REFERENCES PAYMENT(PAYMENTID)
);

----ADMIN_PHONENUMBER TABLE ----

CREATE TABLE ADMIN_PHONENUMBER
(
ADMIN_ID CHAR(6),
PHONENUMBER CHAR(10)

-- --- 
CONSTRAINT ADMIN_PHONENUMBER_FK FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

----ADMIN_BUSINESS_USER TABLE ----

CREATE TABLE ADMIN_BUSINESS_USER
(
ADMIN_ID CHAR(6),
USERID CHAR(6)
--- ---
CONSTRAINT ADMIN_BUSINESS_USER_FK1 FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID),
CONSTRAINT ADMIN_BUSINESS_USER_FK2 FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

----RESERVE_PRICE TABLE ----

CREATE TABLE RESERVE_PRICE
(
PRICE INTEGER,
USERID CHAR(6),
ROOM_ID CHAR(6)

CONSTRAINT RESERVE_PRICE_FK1 FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID),
CONSTRAINT RESERVE_PRICE_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

----HOTEL TABLE ----

CREATE TABLE HOTEL
(
HOTELID CHAR(6),
HOTELNAME VARCHAR(50),
LOCATION VARCHAR(50),
EMAIL VARCHAR(50),
USERID CHAR(6)
CONSTRAINT HOTEL_PK PRIMARY KEY (HOTELID),
CONSTRAINT HOTEL_FK FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID)
);

----HOTEL_ROOM TABLE ----

CREATE TABLE HOTEL_ROOM
(
HOTELID CHAR(6),
ROOM_ID CHAR(6)
---  ---
CONSTRAINT HOTEL_ROOM_FK1 FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID),
CONSTRAINT HOTEL_ROOM_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

----HOTEL_PHONE TABLE ----

CREATE TABLE HOTEL_PHONE
(
HOTELID CHAR(6),
PHONENUMBER CHAR(10)

CONSTRAINT HOTEL_PHONE_FK FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
);

---- RESERVE TABLE ----

CREATE TABLE RESERVE
(
ROOM_ID CHAR(6),
USERID CHAR(6),

CONSTRAINT RESERVE_FK1 FOREIGN KEY (USERID) REFERENCES REGISTER_USER(USERID),
CONSTRAINT RESERVE_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);


alter table REGISTER_USER
add constraint REGISTER_USER_chk check (NIC  like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][v-V]');

alter table REGISTER_USER
add constraint REGISTER_USER_chk2 check (USERID  like '[GB][U][0-9][0-9][0-9][0-9]');

alter table CUSTOMERAGENT
add constraint CUSTOMERAGENT_chk check (EMPID  like '[C][A][0-9][0-9][0-9][0-9]');

alter table ADMIN
add constraint ADMIN_chk check (ADMIN_ID  like '[A][D][0-9][0-9][0-9][0-9]');

alter table ROOM
add constraint ROOM_chk check (ROOM_ID  like '[R][I][0-9][0-9][0-9][0-9]');

alter table HOTEL
add constraint HOTEL_chk check (HOTELID  like '[H][I][0-9][0-9][0-9][0-9]');

alter table PAYMENT
add constraint PAYMENT_chk check (PAYMENTID  like '[P][I][0-9][0-9][0-9][0-9]');